# Diversity, Non-discrimination and Fairness

To ensure the trustworthiness of the STRATIF-AI platform, priority should be given to inclusion and diversity at every stage of the project lifecycle. Efforts to address historical biases, incompleteness, and governance models to mitigate the risk of unintended prejudice and discrimination should be made. The design of STRATIF-AI system will adhere to a user-centric approach, facilitating accessibility for all individuals, irrespective of demographic factors. This will specifically include ensuring accessibility for persons with disabilities.

## Avoidance of unfair bias

### ALTAI Assessment {.unnumbered}

Throughout development, consideration will be given to the diversity and representativeness of end-users and subjects within training data. Testing protocols will be tailored to rectify potential biases, to ensure integrity and impartiality of the platform across user demographics and application scenarios. Educational initiatives aimed at cultivating awareness among AI designers and developers regarding bias and its ethical ramifications will be initiated, fostering a culture of accountability. Mechanisms for identifying and resolving issues pertaining to bias or discrimination within the STRATIF-AI platform will be established within clear communication channels. Discourse with impacted communities, particularly at-risk patient subgroups, will be conducted to ensure that the STRATIF-AI project consortium's conception of fairness resonates with diverse perspectives. A quantitative analytical framework will be embraced to measure and evaluate the efficacy the applied definition of fairness, and institute mechanisms to achieve as such. 

### Represent diversity in data

**Description** Inclusive representation of patients of specific (under-represented) ***subgroups*** in data will be assessed against an acceptable ***threshold*** and rectified or reported accordingly. 

***subgroups:*** patients; patients with stroke; patients at risk of stroke; patients without stroke;   *language; education; age; disability; ethnicity; gender; migration status; socio-economic status;*  
***threshold:*** *reasonable representation; if zero; report in prediction uncertainty*  

**Owner**  

- WP4
- WP5
- WP6

**Key Personnel**

- medical staff *TBD*
- patients/patient representatives *TBD*
- WP3

**Schedule**  At any point, before end of project. 

**Stroke Phase** EACH (3)

**Actionable tasks**  

* appoint key personnel
* define at-risk patient subgroups
* define acceptable thresholds
* feedback from patient representatives/experts
* assess data
* report in publication
* note challenge of oversimplified categorization

### Monitor bias 

**Description** A ***system*** to ***periodically*** monitor bias in different project ***stages*** must be implemented.

***system:*** *prototype for system*  
***periodically:*** *TBD*  
***stages:*** training data preparation; federated learning; model tweaking; prediction modelling   

**Owner**  

- WP2

**Key Personnel**

- technical staff *TBD*
- WP4
- WP5
- WP6
- WP3

**Schedule**  At any point, before end of project. 

**Stroke Phase** ALL

**Actionable tasks**  

* appoint key personnel
* create bias testing pipelines
* define parameters
* send pipelines to necessary spaces (e.g., clinical partners)
* pilot bias testing in preliminary study
* report output
* publication of tool/pipeline

### Assess prediction bias

**Description** System ***outputs*** will be assessed to ensure there is no acceptable  ***difference*** between patient ***subgroups***. 

***outputs:*** technical assessments bias (e.g., model output score and prediction discrepancy); clinical bias assessments (e.g., PROBAST)
***difference:*** *TBD; quantitative threshold; acceptable margin of error;*  
***subgroups*** *gender; sex; ethnicity; education; health history; disability; socio-economic background*

**Owner**  

- WP2

**Key Personnel**

- technical staff *TBD*
- WP3

**Schedule**  At any point, before end of project. 

**Stroke Phase** ALL

**Actionable tasks**  

* appoint key personnel
* define parameters model outputs
* define patient subgroups
* define thresholds
* feedback on thresholds
* publication of results

### Implement bias reporting system

**Description** A system for ***end-users*** to make reports about ***bias*** should be established within the platform and ***periodically*** be evaluated.

***end-users:*** medical professionals, patients  
***bias:*** *any discrimination; process protocol for what constitutes bias; response;*   
***periodically:*** *TBD*     

**Owner**  

- WP2

**Key Personnel**

- technical staff *TBD*
- design staff

**Schedule**  At any point, before end of project. 

**Stroke Phase** ALL

**Actionable tasks**  

* appoint key personnel
* determine evaluation schedule
* outline process protocol for updates upon substantial bias
* design and validate system

### Cultivate ethical awareness

**Description** A ***strategy*** to ensure awareness about ethical issues and accountability for the system, tailored to specific ***stakeholders***, will be designed and executed. 

***strategy:*** workshop series; training programme; accountability declaration;   
***stakeholders:*** developers; doctors; clinicians; care-workers; patients; family members; technical designers; project managers; 

**Owner**  

* WP3

**Key Personnel**

* all relevant leads

**Schedule**  At any point, before end of project. 

**Stroke Phase** ALL

**Actionable tasks**  

* write up workshop paper
* create training package materials
* interview study with experts
* design accountability declaration for project partners
* publish memorandum

### Assess fairness across use-setting

**Description** The fairness of system ***outputs*** across different ***use-settings*** needs to be quantitatively evaluated to minimize risk of unfair prediction values for specific locations/services. 

***outputs:*** *prediction intervals; prediction types; accessibility; speed;*     
***use-settings:*** hospitals; homes; resource differences; medical equipment; medical staff;   

**Owner**  

* WP7

**Key Personnel**

* WP4
* WP5
* WP6
* WP3

**Schedule**  At any point, before end of project. 

**Stroke Phase** EACH (3)

**Actionable tasks**  

* appoint key personnel
* design study to assess fairness across contexts
* define parameters to study
* pre-register study
* pilot with prototype of tool or collect data within clinical trials
* publication of results

### Assess and build trust within vulnerable patient groups

**Description** Degree of ***trust*** in the STRATIF-AI platform, determined by ***end-users***, will be quantified. An assessment of trust within specifically vulnerable patient and care-work ***subgroups*** will be assessed and measures to respond to discrepancies between subgroups devised. 

***trust:*** *TBD; operational definition of trust*  
***end-users:*** medical professionals; patients with stroke; patients at risk of stroke; patients without stroke  
***subgroups:*** *language; education; age; disability; ethnicity; gender; migration status; socio-economic status;*    

**Schedule**  At any point, before end of project. 

**Stroke Phase** ALL

**Owner**  

* WP3

**Key Personnel**

* patient representatives
* medical staff

**Actionable tasks**

* appoint key personnel
* define degrees of trust or conception of trust
* design questionnaire/interview to survey trust of system
* pre-register survey
* execute survey with key personnel
* report outcomes
* assess how outcomes vary within patient subgroups
* disseminate outcomes in STRATIF-AI pilot studies and solicit feedback
* publication on trust and diversity in digital twins

::: {.callout-note}
This requirement will constitute a part of the trust study designed to fulfill Requirement 1.1.4 Establish degree of trust.
::: 

### Implement fairness reporting system

**Description** A system to report whether the system ***outputs*** are evaluated as ***accessible*** must be implemented within the platform for ***end-users***.  

***outputs:** *prediction intervals; recommendations; rehab demos;*   
***accessible:*** comprehensible in language; available to varying levels of resource access; feasible within time budgets;    
***end-users:*** patients; medical staff  

**Schedule**  At any point, before end of project. 

**Stroke Phase** EACH (3)

**Owner**  

* WP7

**Key Personnel**

* patient representatives
* medical staff
* design staff *TBD*

**Actionable tasks**

* appoint key personnel
* define parameters output and feasibility
* prototype system in apps/platform
* pilot study
* report results
* publication

## Accessibility and universal design

### ALTAI Assessment {.unnumbered}

Measures to prioritize inclusivity and accessibility of STRATIF-AI to a wide and diverse user-base will be taken. Assessment will be conducted to gauge the usability of the AI system's user interface for individuals with special needs, disabilities, or those at risk of exclusion. Efforts will be made to guarantee that information about the AI system, as well as its user interface, remains accessible and usable for users of assistive technologies, particularly those relevant for patients of stroke. Furthermore, Universal Design principles will be integrated into various stages of planning and development, where applicable, to enhance accessibility for all users.

### Utilize inclusive design principles

**Description** The platform must be designed, tested, and trained by ***methods*** to account for ***needs*** of vulnerable ***subgroups*** of ***end-users***. 

***methods:*** *TBD*
***needs:*** *TBD*  
***end-users:*** medical staff; patients;  
***subgroups:*** *language; ethnicity; socio-economic background; health history; trust;*  

**Schedule**  At any point, before end of project. 

**Stroke Phase** EACH (3)

**Owner**  

* WP3

**Key Personnel**

* patient representatives *TBD*
* medical staff *TBD*
* design staff *TBD*

**Actionable tasks**

* appoint key personnel
* this will move to a different owner after preliminary assessment
* define set of needs that should be accessible
* identify different patient subgroups
* conduct interviews/solicit patient feedback
* design protocol to evaluate prototype design
* move WP owner to design staff
* pilot design and solicit feedback

### Assess financial risk of unfair design

**Description** The system ***outputs*** must be critically evaluated to avoid ***risks*** of financial misuse in different ***clinical settings***.

***outputs:*** *prediction intervals; discrepancy between clinician and prediction; discrepancy between patient and clinician;*    
***risks:*** *insurance system; financial overhead; costs of stay*   
***clinical settings:*** hospitals; rehab centers    

**Schedule**  At any point, before end of project. 

**Stroke Phase** EACH (3)

**Owner**  

* WP7

**Key Personnel**

* patient representatives
* medical staff
* design staff (TBD)
* technical staff (TBD)

**Actionable tasks**

* appoint key personnel
* define parameters 
* perform evaluation
* e.g., via experimental study/ pilot/ lit review
* update outputs
* institute necessary data protections

## Stakeholder participation

### ALTAI Assessment {.unnumbered}

STRATIF-AI is a project with a significant diversity in stakeholders. Consistent feedback and co-creation will be maintained with stakeholders during early stages of project development. Mechanisms to ensure sustained stakeholder involvement after the implementation of the platform will also be designed.

### Incorporate patient perspectives

**Description** Feedback and perspectives about system ***functions*** from representatives of patient ***subgroups*** will be solicited ***periodically*** and incorporated into system development.

***subgroups:*** *gender; disability; ethnicity; socio-economic status*    
***periodically:*** *TBD*  
***functions:*** *model output, prediction intervals; design; overall trust; use;*    

**Schedule**  At any point, before end of project. 

**Stroke Phase** EACH (3)

**Owner**  

* WP3

**Key Personnel**

* patient representatives

**Actionable tasks**

* appoint key personnel
* define parameters
* design study or format
* design a reproducible questionnaire that can easily be answered
* pass to WP4, WP5, WP6
* design process protocol for responding to feedback
* design procedure for disseminating feedback
* publication on patient perspectives

### Foster end-user feedback

**Description** A system for ***end-users*** to provide ***feedback*** should be established within the platform and ***periodically*** be evaluated.

***end-users:*** medical professionals, patients;    
***discrepancies:*** *format of feedback;*   
***periodically:*** *TBD;* 

**Stroke Phase** ALL

**Owner**  

* WP2

**Key Personnel**

* design staff
* technical staff

**Actionable tasks**

* appoint key personnel
* determine evaluation schedule
* design and validate system

::: {.callout-note}
Requirements 5.2.1; 5.3.1; and 5.3.2 are closely related. Requirement 5.2.1 is concerned with design of the platform for end-users who may be patients or medical staff with diverse accessibility needs. Requirement 5.3.1 is concerned with more general inclusivity of specifically patients in the overall development and goals of the STRATIF-AI platform. Requirement 5.3.2 refers to a feedback system---again closely linked with several other requirements---to provide information to enable the fulfillment of requirements 5.2.1 and 5.3.1. 
:::