# Societal and Environmental Well-being

The impacts of the AI system on the wellbeing of society must be considered throughout its life cycle. A system which is encountered in aspects of daily life---e.g., healthcare---has the potential to negatively impact mental health and emotional wellbeing. Such effects must be carefully considered and mitigated. Additonally, the sustainability of the AI system under development must be a point of discussion, such that the development and utilization of an AI system benefits all human beings, including future generations. Finally, the system must not undermine democratic processes or pose a threat to democratic society. 

## Environmental Wellbeing

AI systems should be as environmentally friendly as possible. The development, deployment and use-processes must therefore be assessed in terms of energy consumption and resource demands, in order to minimize waste. During the development of the STRATIF-AI project, the potential of negative harm on the environment needs to be systematically considered. Measuring the environmental impact through energy consumed and carbon emissions will be built into the development pipeline. Measures to reduce these impacts will be subsequently explored. 

### Identify environmental impact of model development

**Description** The ***environmental impacts*** of ***system development processes*** need to be measured or estimated by appropriate ***methodologies***.
 
***environmental impacts:*** carbon emissions; energy used;    
***system development processes***: model training; *other process with footprint?*
***methodologies:*** environmental impact assessment tools, e.g., carbon tracking tools like CodeCarbon for Python
 
**Owner**  

* WP2

**Key Personnel**

* technical staff

**Schedule**  At any point, before end of project.  

**Stroke Phase** ALL

**Actionable tasks**  

* appoint key personnel
* define parameters (environmental and possibly costly processes)
* define method to estimate costs
* report costs to consortium/in documentation 

### Reduce environmental impact

**Description** A SOP which outlines acceptable ***thresholds*** and a resulting process protocol must be developed within an ***appropriate timeframe*** to mitigate environmental impacts. 
 
***thresholds:*** *limit for carbon emissions for model training; limit for time spent model training*  
***appropriate timeframe:*** *TBD*  

**Owner**  

* WP2

**Key Personnel**

* technical staff
* WP3

**Schedule**  At any point, before end of project.  

**Stroke Phase** ALL

**Actionable tasks**  

* appoint key personnel
* define parameters/ thresholds and procedures
* draft SOP (WP3)
* develop SOP for modelling team
* publish SOP

## Impact on Work and Skills

### ALTAI Assessment {.unnumbered}

STRATIF-AI will be designed with a human-in-command governance system and to prioritize the epistemic authority of physicians. However, as a clinical decision-support system, STRATIF-AI will potentially have significant impacts on human work and work arrangements, necessitating a thorough assessment through an implementation strategy. While medical professionals will play a central role in the development pipeline of STRATIF-AI, broader inclusion and consultation with potentially affected workers and their representatives will be carried out. Measures to minimize the system's impact on human work will be implemented, following an in-depth investigation of STRATIF-AI's potential risks regarding the de-skilling of doctors or the alteration of training procedures and experiential learning.

### Investigate impact on work arrangements

**Description** ***Methodology*** to assess ***concerns*** of potentially affected ***workers*** must be devised to inform the platform's implementation strategy. 
 
***methodology:*** *TBD; stakeholder interviews; workshops; focus groups*  
***concerns:*** *TBD; de-skilling; mistrust*  
***workers:*** doctors; nurses; insurance personnel; training personnel; rehabilitation specialists; physiotherapists; *any affected working persons involved in the care of stroke patients*  

**Owner**  

* WP3

**Key Personnel**

* WP4
* WP5
* WP6
* WP7

**Schedule**  At any point, before end of project.  

**Stroke Phase** EACH (3)

**Actionable tasks**  

* appoint key personnel
* define full set of at-risk workers
* conduct workshops with key personnel 
* design interview to elicit concerns from workers
* write process protocol for implementation strategy
* feed into HIC concept

::: {.callout-note}
In the initial co-creation workshop series, participants expressed concerns that integrating the STRATIF-AI platform into clinical practice too early and without warning may limit the natural experience-building process that physicians generally undergo.
:::

##  Impact on Society at large or Democracy

### ALTAI Assessment {.unnumbered}

Potential ramifications on society at large and democracy will be considered throughout the STRATIF-AI project cycle. To assess the societal impact of the AI system's utilization beyond those to immediate end-users and subjects, we will solicit feedback throughout planned pilot and clinical trial studies. A key aspect of the STRATIF-AI platform is developing an infrastructure to empower citizens to monitor their overall health and wellbeing while screening for risk of stroke---which will contribute to the benefit of society at large. The STRATIF-AI platform is not at risk of undermining democratic principles or adversely affecting democracy. 

### Solicit citizen feedback

**Description** Include diverse ***citizens*** in discussions at relevant ***stages*** of the STRATIF-AI pipeline. 
 
***citizens:*** citizens; hospital workers; *persons who may be overlooked in stakeholder discussions*  
***stages:*** *TBD; public representation of STRATIF-AI project; youtube; reddit*  

**Owner**  

* WP3

**Key Personnel**

* all WP leads

**Schedule**  At any point, before end of project.  

**Stroke Phase** ALL

**Actionable tasks**  

* appoint key personnel/ WP leads
* define parameters, i.e. stakeholders who may be overlooked
* clarify potential procedures within WP tasks to incorporate discussions
* assess input from stakeholders
* disseminate information 
